// <auto-generated />
using MetersDesktopApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MetersDesktopApp.Migrations
{
    [DbContext(typeof(MetersDbContext))]
    [Migration("20200330204825_migration0002_mod_requerimenos")]
    partial class migration0002_mod_requerimenos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MetersDesktopApp.Models.Meter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("IdCp")
                        .HasColumnType("text");

                    b.Property<string>("IdCs")
                        .HasColumnType("text");

                    b.Property<string>("IdTrafo")
                        .HasColumnType("text");

                    b.Property<bool>("IsOn")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("meters");
                });
#pragma warning restore 612, 618
        }
    }
}
